"""Parse and pretty-print state.json for status_train.sh."""
import json
import sys

state_file = sys.argv[1]
d = json.load(open(state_file, encoding="utf-8"))

status   = d.get("status", "?")
cur      = d.get("current_update", 0)
tot      = d.get("total_updates", 0)
pct      = d.get("progress_percent", 0)
ts       = d.get("total_timesteps", 0)
sps      = d.get("steps_per_second", 0)
eta      = d.get("eta_seconds", 0)
elapsed  = d.get("elapsed_seconds", 0)
rw       = d.get("mean_reward", 0)
mx       = d.get("max_reward", 0)
mn       = d.get("min_reward", 0)
wr       = d.get("win_rate", 0)
eps      = d.get("total_episodes", 0)
pl       = d.get("policy_loss", 0)
vl       = d.get("value_loss", 0)
ent      = d.get("entropy", 0)
kl       = d.get("approx_kl", 0)
cf       = d.get("clip_fraction", 0)
gn       = d.get("grad_norm", 0)
lr       = d.get("learning_rate", 0)
gpu      = d.get("gpu", {})
gname    = gpu.get("device_name", "CPU")
gvram_a  = gpu.get("vram_allocated_mb", 0)
gvram_t  = gpu.get("vram_total_mb", 0)
gvram_p  = gpu.get("vram_percent", 0)
gtemp    = gpu.get("temperature_c", "N/A")
gutil    = gpu.get("gpu_utilization_percent", "N/A")

m, s = divmod(int(elapsed), 60)
eta_m, eta_s = divmod(int(eta), 60)

print(f" Status   : {status.upper()}")
print(f" Progresso: Update {cur}/{tot}  ({pct:.1f}%)  |  {ts:,} timesteps")
print(f" Tempo    : {m:02d}:{s:02d} decorrido  |  ETA {eta_m:02d}:{eta_s:02d}  |  {sps:.0f} steps/s")
print("")
print(" -- Performance --")
print(f" Recompensa : mean={rw:+.3f}  max={mx:+.3f}  min={mn:+.3f}")
print(f" Win Rate   : {wr:.1%}  ({eps} episodios concluidos)")
print("")
print(" -- PPO Losses --")
print(f" Policy Loss  : {pl:+.5f}")
print(f" Value Loss   : {vl:.5f}")
print(f" Entropy      : {ent:.4f}")
print(f" Approx KL    : {kl:.5f}")
print(f" Clip Fraction: {cf:.3f}")
print(f" Grad Norm    : {gn:.4f}")
print(f" LR           : {lr}")
print("")
print(" -- GPU --")
print(f" Dispositivo : {gname}")
print(f" VRAM        : {gvram_a:.0f} / {gvram_t:.0f} MB  ({gvram_p:.1f}%)")
print(f" Temperatura : {gtemp} C")
print(f" Utilizacao  : {gutil} %")
